### ISSUE TITLE
Can I use another framework or programming language for backend?

### ISSUE THREAD

**Issue by yiwan** [Wiredcraft/test-fullstack#11]
I know the first `Requirement` says I need use `loopback`, and I've tried it, unfortunately not a fan.
I've seen your `test-backend` doesn't specified which framework/language to use, so why `test-fullstack` does？

**Comment by makara** [comment]
You can, just give us a proper reason for your choice.

**Comment by yiwan** [comment]
I may use `Rails` or `Django`, so `Ruby` or `Python`.

1. better document
2. better community
3. more robust

I've tried `Rails` and `Django` earlier(walk through their quick guide), feels much better than `LoopBack`.
And in my opinion `Ruby` or `Python` at least better then JavaScript 🙈, for doing backend stuff.

**Comment by makara** [comment]
Use Django then. Nobody knows Rails here.

**Comment by yiwan** [comment]
@makara 👌
