### ISSUE TITLE
Development Questions from Kun

### ISSUE THREAD

**Issue by rankun203** [Wiredcraft/test-fullstack#33]
Hi everyone, Kun here,

So I’ve just started working on this test project today and had a few questions, any input would be greatly appreciated :)

- [x] 1. Feature: Since users will need to login, but the User Stories didn't mention such features, also the requirements mentioned to include OAuth, so I'm thinking about including Github as a login provider. A user will see a login screen with only one button says [Sign In With Github], he(she) clicks on it, and finishs the OAuth process, boom, it will take him(her) to the talk listing page. Is that OK?
  - Anonymous: view list of talks, sign in.
  - Logged in users: create new talks, vote for a lightning talk, sign out.
- [x] 2. Feature: Can a user vote for more than one talks?
- [x] 3. Feature: Any _commenting on lightning talks_ related feature required?
- [x] 4. Any dedicated search / filter feature is required? The “filter feature” mentioned in the document I’m gonna make it so when users click on the creator of a talk, talk listing will be filtered just like Hacker News does.
- [x] 5. Question:

  > Use a NoSQL DB and build a filter feature that can filter records with some of the attributes such as username

  I'm not quite sure if I get it correctly, so if I don't use MongoDB's query language and that's possibly the only language Mongo supports, then I'll need to use some other databases right? Or maybe I should implement a custom indexing strategy and store everything in Redis? Or, just save it in memory and create indexes in memory?
- [x] 6. Question: Just to make sure, since using a packaging tool like Parcel is pretty easy as well, saves a lot of time configuring Webpack and Babel, I'm gonna just use Parcel with TypeScript, if you guys have any preference please let me know :)

Current requirements I've been working on:

- [Fullstack - recruitment-test](https://wiredcraft.gitbook.io/recruitment-test/coding/fullstack)
- [This Github project #8e99ae7
](https://github.com/Wiredcraft/test-fullstack/tree/8e99ae7a9d4ad47d9c3d3e4e035a936b037a3cf4)

Since two descriptions are slightly different, if I have any more questions I'll put it in this issue.

Thanks for the effort.

**Comment by makara** [comment]
Generally, please consider it's more an open requirement and you complete it with your knowledge and assumptions, and of course, with limited time.

1. Sure.
2. Up to you.
3. Up to you.
4. Sure.
5. Redis is acceptable.
6. We always prefer JS over TS. It's a test about JS skill after all. Don't make it too difficult for us.

And regarding the difference, please refer to my email.

**Comment by rankun203** [comment]
@makara Thank you for the reply. It helps a lot. For the 6th question I’ll continue with JavaScript instead of TypeScript.

**Comment by makara** [comment]
Sure. Closing.
