### ISSUE TITLE
Mayi's issues for development

### ISSUE THREAD

**Issue by flyingant** [Wiredcraft/test-fullstack#5]
Hi, I am Liu Cheng (aka 'MaYi'). 

After had a nice talk at WiredCraft office this Monday, I was assigned to build this app with React and Loopback, Redis. 

Well I'm really new on nodejs, loopback and redis and start to study everything from Tuesday then I am stuck when developing the **loopback-based** back-end server today and hope you guys could help to provide some advices to me.

1. is there any best way to debug the code? (debugger?)
2. any suggested IDE for loopback?

Also in the past two days, I spent a few hours and finished the code for front-end web application and built a very simple java-based server for testing. Vist the link [http://staging.flyingant.me/i/home](http://staging.flyingant.me/i/home) to check out.(^_^). Later I will use the loopback-based server instead my test server.
![623e9ef0-eea3-47de-ad55-d8f8f2f531e1](https://cloud.githubusercontent.com/assets/1773209/16646171/4ae6f8f8-445b-11e6-9e7e-c16e60a6dc6e.png)

Thanks

**Comment by wwayne** [comment]
Hi, we mainly use this library [debug](https://github.com/visionmedia/debug) for debugging and my best friend `console.log`, and I don't think there is a IDE for loopback, it just a framework based on node.js, so I think just use the tool that you used for developing JS is enough.

**Comment by EcutDavid** [comment]
Hi @flyingant, I guess you are wondering how to developer nodejs application with the debugging experience like Java, C#.
You can use IDE like https://www.jetbrains.com/webstorm/. Nearly the same debugging experience.

**Comment by EcutDavid** [comment]
By the way, there is a small styling problem in your current demo site.

If we add more talks, and let's scroll down.
![image](https://cloud.githubusercontent.com/assets/10692276/16647645/c4c28456-4462-11e6-9915-e121dcf65694.png)

The background color become weird.

**Comment by EcutDavid** [comment]
Another suggestion:
It's better for you to remove the https://github.com/flyingant/test-fullstack/blob/master/app/build/app.bundle.js in git repo, since it's not your source code and it will make git repo became a giant size.

Building the bundle in server instead of build and commit it to repo.

**Comment by z4rd** [comment]
Hi, MaYi, I'm Jan, and here to review your CSS work.
Could you try to make the interface be simply styled if you have a next step, 
no need to over do it, align the boxes & make the style consistent is enough.
It'll be better for us to know your basics of layout.

**Comment by flyingant** [comment]
@EcutDavid @wwayne Thanks for your advices. Yep, I'm gonna fix the css issue and remove the .bundle file in source code tree later.

**Comment by flyingant** [comment]
@z4rd Hi, Jan. Thank you! I am gonna take your advices and it would be grateful if you could guide me to make it better.

Thanks.
