### ISSUE TITLE
Some questions before starting

### ISSUE THREAD

**Issue by UriLucioWald** [Wiredcraft/test-fullstack#7]
1) User login - Should I support user sign up? 
If supporting sign up should I support email verification? 
If not supporting sign up, should I support a list of users or anybody can just login?

2) Should I support comments threading ?
  `comment a`
  `- b reply to a`
  `-- c reply to b`
  `- d reply to a`

3) Should I support page refreshing  - when watching the lightning talks if some other users are currently  ranking talks , should my page refresh accordingly?

4) Should the lightning talk format be as following?
Number, vote up , title
X point by Username followed by time
example : 
20. Automated API Testing
1 point by antfie 49 minutes ago | hide | past | web | discuss

5) Can a user vote several times for the same lightning talk?

6) Should the user see his lightning talks in front of the other talks?

7) When a user hits the lightning talk should he see all the users who liked that talk?

8) Can the user upload a link to the lightning talk page?

**Comment by xavierchow** [comment]
Thanks for confirmation.

> 1) User login - Should I support user sign up? 

It depends on you, for me a list of fix users should be fine.

> 2) Should I support comments threading ?

Yes.

> 3) Should I support page refreshing

You can add this feature if you have time.

> 4) Should the lightning talk format be as following?

You decide it, you don't need to be exactly same as hacker news.

> 5) Can a user vote several times for the same lightning talk?

No.

>6) Should the user see his lightning talks in front of the other talks?
7) When a user hits the lightning talk should he see all the users who liked that talk?
8) Can the user upload a link to the lightning talk page?

Good to have, but we don't want to make the test too complex.

**Comment by xavierchow** [comment]
Hey @UriLucioWald , if you're uncomfortable with any part of the test you can just drop some features cause we don't need a fledge application, the main purpose of the test is to see how you organise your code and how you communicate with others when resolving problems.
