### ISSUE TITLE
OPT: short polling cache

### ISSUE THREAD

**Issue by JoyCJay** [Wiredcraft/test-fullstack#70]
front-end use fetch method to exchange with back-end.

request from postman can be cached 304
but request from navigator always 200. (Etag and If-None-match)

see detail in attachment

![image](https://user-images.githubusercontent.com/32035698/158333426-d6e86b3c-430b-4968-ab50-7f527141f9ab.png)
![image](https://user-images.githubusercontent.com/32035698/158333793-843755ef-0c8b-46e6-9fb9-39ee4d0374e5.png)

**Comment by rankun203** [comment]
The issues list for this repo serves the purpose of improving test-fullstack tests quality, since this ticket is not reflecting on the quality of the test itself, I hereby mark it as invalid and close it.
