### ISSUE TITLE
About the required features

### ISSUE THREAD

**Issue by kenchme** [Wiredcraft/test-fullstack#8]
Hi, I am designing this small project. I am not sure about the exactly required features. As I saw in the other issue [#7](https://github.com/Wiredcraft/test-fullstack/issues/7), the requirement is quite open, thus I decided to write my ideas down here and expect your feedback if you found anything wrong!
### Backend

Here's what I am going to code for the backend API (and I was asked to use express)
User
- Register / Login / Logout

Talk (Protected APIs - Login required)
- Get a list of talks (title, description, postedBy, rating)
- Create a new talk by a logged-in user
- Rate a specific talk (+1 or -1). One user cannot rate the same talk multiple times.

The features I am not going to code.
1. Delete user/talk
2. Pagination
3. comments for talks
### Frontend

I am going to use AngularJS 1 & bootstrap for the frontend, to quickly build a prototype UI layout.

Please comment if you found anything inappropriate. Thanks!

**Comment by makara** [comment]
Sounds good. Please go ahead.
